baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Gentics Mesh Hugo Example"
theme = "mesh-demo"
relativeURLs = false
canonifyurls = false

copyright = "Apache License 2.0"

[author]
  name = "John Doe"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  justifyContent = false  
